[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"
  SECRETS_SCAN_ENABLED = "false"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
